### ISSUE TITLE
stuck trying to get prices

### ISSUE THREAD

**Issue by thirstaidkit** [rengelking/hodlerfolio.com#2]
stuck at "Retrieving latest prices, please wait..."
% bar stays at 100

**Comment by rengelking** [comment]
Hi, most likely your internet connection was down or coinmarketcap.com was down, as that is where it pulls the prices from

**Comment by thirstaidkit** [comment]
double checked and that was not the case. Only been able to get it to work on my phone and even then it did not recognize Quantstamp (QSP), and two other small cryptos.

**Comment by tmlee** [comment]
May i suggest looking at the CoinGecko API as for your consideration https://www.coingecko.com/api 

Open to help answer any questions. Cheers!

**Comment by rengelking** [comment]
Thanks, sorry for the delay, I have updated to CoinGecko, as CoinMarketCap ended up putting up a complete paywall; CoinGecko is fantastic, I don't have to dig for the coin images, and it is running much better.

**Comment by tmlee** [comment]
Thats awesome to know! Feel free to reach out to me if you have any questions or issues
